### ISSUE TITLE
frequently doesn't respond to git invocation (

### ISSUE THREAD

**Issue by vassudanagunta** [coteditor/CotEditor#1180]
Most of the time when I invoke a git command that uses an editor, such as `git commit` or `git rebase -i`, Cot comes up as expected. But once in a while, maybe 5% of the time, Cot doesn't open. Sometimes the `Force Quit Applications` window shows CotEditor along with `not responding`, in which case I have to kill that too. Then when I retry, it will come up. But sometimes after a LONG wait (like 5 to 10 seconds). This has been happening to me for a while, so this isn't a recent regression or even tied to a recent release of macOS. 

In my `.gitconfig`:

```yaml
core.editor=cot --wait
```

I'm using CotEditor Version 4.0.3 (459)

<details><summary>traceback after `CTRL-C`-ing the hung `git commit`</summary>
<pre><code>
hint: Waiting for your editor to close the file... 
^CTraceback (most recent call last):
  File "/usr/local/bin/cot", line 411, in <module>
    main(args, stdin)
  File "/usr/local/bin/cot", line 315, in main
    client_name = system.tell('get path of application file of application '
  File "/usr/local/bin/cot", line 138, in tell
    return run_osascript(script, is_async)
  File "/usr/local/bin/cot", line 106, in run_osascript
    stdout, stderr = p.communicate(script.encode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 483, in communicate
    return self._communicate(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1126, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1227, in _communicate_with_select
    rlist, wlist, xlist = select.select(read_set, write_set, [])
KeyboardInterrupt
error: There was a problem with the editor 'cot --wait'.
</code></pre>
</details>

**Comment by vassudanagunta** [comment]
This hasn't happened in a while. so let's assume it was fixed in one of the updates. 🎉

**Comment by 1024jp** [comment]
Sorry, I could not actively find out the cause and fix it.
And, thank you for the update.
