### ISSUE TITLE
CotEditor CLI 2.4.1 error on macOS Sierra.4PB1&2

### ISSUE THREAD

**Issue by Chamiu** [coteditor/CotEditor#675]
CotEditor 3.1.3 installed on macOS Sierra.4PB1&2

````
$ ln -s /Applications/CotEditor.app/Contents/SharedSupport/bin/cot /usr/local/bin/cot
````

I try to open ~/.zshrc

````
cot ~/.zshrc
````

1. Launch CotEditor, but not open a document window.
2. control+c at Terminal.app.
3. Terminal.app say.

````
Traceback (most recent call last):
  File "/usr/local/bin/cot", line 340, in <module>
    main(args, stdin)
  File "/usr/local/bin/cot", line 269, in main
    app.launch(background=args.background)
  File "/usr/local/bin/cot", line 139, in launch
    self._pid = system_events.tell(script)
  File "/usr/local/bin/cot", line 122, in tell
    return run_osascript(script, is_async)
  File "/usr/local/bin/cot", line 90, in run_osascript
    stdout, _ = p.communicate(script.encode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1411, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1512, in _communicate_with_select
    rlist, wlist, xlist = select.select(read_set, write_set, [])
KeyboardInterrupt
````

**Comment by 1024jp** [comment]
@Chamiu Do you know if this issue already exists on macOS 10.12.3? or first appeared on the 10.12.4 beta?

**Comment by Chamiu** [comment]
@1024jp As far as I remember no problem on macOS 10.12.3. This issue appear on 10.12.4 betas.

**Comment by 1024jp** [comment]
@Chamiu Ok. Then, I'll check when the stable 10.12.4 is released. Thank you for notifying it.

**Comment by 1024jp** [comment]
@Chamiu Hi, I've just tried this issue on my macOS 10.12.4 beta 5 and couldn't reproduce. Do you still have this problem under your environment or it's already fixed at some time point?

**Comment by Chamiu** [comment]
I try CotEditor 3.1.7 on macOS 10.12.4 beta 5(16E183b) too.

1. input cot .zshrc to Terminal.app
2. launch CotEditor
3. active CotEditir
But CotEditor silent, ctrl+c  to Terminal.app

It turned out different at line number. Terminal.app say.

Traceback (most recent call last):
  File "/usr/local/bin/cot", line 346, in <module> <--
    main(args, stdin)
  File "/usr/local/bin/cot", line 275, in main <--
    app.launch(background=args.background)
  File "/usr/local/bin/cot", line 139, in launch
    self._pid = system_events.tell(script)
  File "/usr/local/bin/cot", line 122, in tell
    return run_osascript(script, is_async)
  File "/usr/local/bin/cot", line 90, in run_osascript
    stdout, _ = p.communicate(script.encode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1411, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1512, in _communicate_with_select
    rlist, wlist, xlist = select.select(read_set, write_set, [])

Console.app not have a log at CotEditor at /Library/log and ~/Library/log.
I want you to tell me if there is a place thinking that there is helpful information.

Sorry, I'm not native English.

**Comment by 1024jp** [comment]
Thanks for your additional info.

I'm interested in what happens if you use the following `cot` script instead of the current one. Could you try this and tell me the result?

`./cot ~/.zshrc`

--

追加情報ありがとうございます。
以下に添付した cot コマンドを試した時にどうなるかに興味があります。

[cot.zip](https://github.com/coteditor/CotEditor/files/838837/cot.zip)

普通の cot コマンド代わりに以下のように実行してみて結果を教えていただけると幸いです。

`./cot ~/.zshrc`

**Comment by Chamiu** [comment]
1. download cot.zip to ~/Downloads/
2. ArchiveUtilitiy unzip cot.zip
3. $ cd 
4. $ cp ~/Downloads/cot ./
5. $ ./cot ~/.zshrc

a. launch CotEditor
b. active CotEditir
c. But CotEditor silent, ctrl+c to Terminal.app

Terminal.app say.

Traceback (most recent call last):
  File "./cot", line 346, in <module>
    main(args, stdin)
  File "./cot", line 275, in main
    app.launch(background=args.background)
  File "./cot", line 139, in launch
    self._pid = system_events.tell(script)
  File "./cot", line 122, in tell
    return run_osascript(script, is_async)
  File "./cot", line 90, in run_osascript
    stdout, _ = p.communicate(script.encode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 799, in communicate
    return self._communicate(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1411, in _communicate
    stdout, stderr = self._communicate_with_select(input)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1512, in _communicate_with_select
    rlist, wlist, xlist = select.select(read_set, write_set, [])
KeyboardInterrupt

**Comment by 1024jp** [comment]
Thanks. It seems the result is the same 😞
I'll consider...

**Comment by 1024jp** [comment]
How about this one? At least, the stack trace may change.

[cot2.zip](https://github.com/coteditor/CotEditor/files/839014/cot2.zip)

**Comment by Chamiu** [comment]
I try CotEditor 3.1.7 on macOS 10.12.4 beta 5(16E183b).
No Problem. Thank you!

... macOS 10.12.4 beta 6 come.

**Comment by 1024jp** [comment]
That's good to hear!
I'll submit CotEditor 3.1.8 uncluding this cot command later today.
Really thank you to helping me to debug🐜🍰

**Comment by Chamiu** [comment]
I try CotEditor 3.1.7 on macOS 10.12.4 beta 6(16E189a).
No problem, fine!
