### ISSUE TITLE
Using cot in Hyper Terminal under Mojave

### ISSUE THREAD

**Issue by zanderzhng** [coteditor/CotEditor#853]
I got the following error while trying to use the `cot` in `Hyper`.
Never had this problem before `Mojave`. Also, it's working good in `Terminal`
```
❯ cot
Traceback (most recent call last):
  File "/usr/local/bin/cot", line 354, in <module>
    main(args, stdin)
  File "/usr/local/bin/cot", line 270, in main
    client_window_id = client.window_id()
  File "/usr/local/bin/cot", line 164, in window_id
    return self.tell('id of window {}'.format(index))
  File "/usr/local/bin/cot", line 121, in tell
    return run_osascript(script, is_async)
  File "/usr/local/bin/cot", line 92, in run_osascript
    raise CalledProcessError(p.returncode, script)
subprocess.CalledProcessError: Command 'tell app "Hyper" to id of window 1' returned non-zero exit status 1
```

**Comment by zanderzhng** [comment]
Fixed, thank you.
